### ISSUE TITLE
Alert should be played higher than the peak detected

### ISSUE THREAD

**Issue by jbochi** [jbochi/feiradetector#8]

**Comment by thiagoss** [comment]
There is a 'volume' element that can be used to increase a signal's volume by software. You can precompute maybe the ideal volume value for some peaks that you might detect.

If you go fancy, maybe the playback pipeline should have a level itself and it could be used to control the volume until it reaches the noise detected at the room previously.

**Comment by jbochi** [comment]
Thanks for your suggestions, Thiago. I'll try to implement the first idea.

On Tue, Jul 31, 2012 at 12:17 AM, Thiago Santos <
reply@reply.github.com

> wrote:
> 
> There is a 'volume' element that can be used to increase a signal's volume
> by software. You can precompute maybe the ideal volume value for some peaks
> that you might detect.
> 
> If you go fancy, maybe the playback pipeline should have a level itself
> and it could be used to control the volume until it reaches the noise
> detected at the room previously.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jbochi/feiradetector/issues/8#issuecomment-7388782

## 

Juarez
